### ISSUE TITLE
请问有简单的部署指南和requirement.txt参考吗？

### ISSUE THREAD

**Issue by wpcwzy** [ixiaohei-sakura/MWConsole#1]
或者每个模块的简要注释也行2333想本地部署一个试验一下，可以的话帮忙写一写

**Comment by ixiaohei-sakura** [comment]
现在其实还没好，但是我已经将requirement.txt放上去了，只有部分写完了，但是MCDR交互和网页交互、连接认证都还没好
介绍一下安装步骤：
下载项目到本地，打开back_end文件夹，进入mwclibs文件夹，用python3运行mserver.py, 可能会有各种各样的错误，因为目前只在我的电脑上测试了
看过了你的几个小项目，考虑帮忙美化下这个项目的网页页面？哈哈
配置文件放在了目前文件及里面的config文件夹中。
可以看看或者删掉重启程序跟着引导配置
这个项目通过了mac与Ubuntu系统上的测试，正好缺windows的测试
如果有任何报错请在这里提交issue!
感谢

**Comment by wpcwzy** [comment]
好的，感谢！
